apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-sim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bridge-sim
  template:
    metadata:
      labels:
        app: bridge-sim
    spec:
      containers:
        - name: bridge-sim-container
          image: "ghcr.io/lmartinking/bridge-sim:latest"
          env:
            - name: DASH_URL_BASE_PATHNAME
              value: "/bridge-sim/"
---
apiVersion: v1
kind: Service
metadata:
  name: bridge-sim-service
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: bridge-sim
---
# # This middleware is used to strip "/quik" from the HTTP request path,
# # as the container itself does not know what its route prefix is.
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: middleware
# spec:
#   stripPrefix:
#     forceSlash: false
#     prefixes:
#       - /bridge-sim
# ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bridge-sim-ingress
  annotations:
    ingress.kubernetes.io/class: "traefik"
    #traefik.ingress.kubernetes.io/router.middlewares: bridge-sim-middleware@kubernetescrd  # {namespace}-{name}@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: irrationalidiom.com
      http:
        paths:
          - path: /bridge-sim
            pathType: Prefix
            backend:
              service:
                name: bridge-sim-service
                port:
                  number: 80